In [17]:
#pandas : 데이터 프레임을 효과적으로 다룰 수 있도록 도와주는 라이브러리
import pandas as pd
import numpy as np

storeframe = pd.DataFrame({
                           'unit price' : [1000,280,900],
                           'number' :[25,120,30]
                          },index = ['store1','store2','store3'])
storeframe




unit price  number
store1        1000      25
store2         280     120
store3         900      30

In [13]:
import pandas as pd
import numpy as np

#np.random.rand(3,2):3행 2열 0-1사이의 data
df = pd.DataFrame(np.random.rand(3,2), index=['m1','m2','m2'],columns=['price','num'])
df



price       num
m1  0.830823  0.647249
m2  0.045656  0.709564
m2  0.968919  0.327931

In [17]:
#특정 열 접근 :df[컬럼명]
print(df['num'])
print(df['num']>0.5)
df2 = df[df['num']>0.5]
print(df2)
#전치 : df.T
print(df2.T)

m1    0.647249
m2    0.709564
m2    0.327931
Name: num, dtype: float64
m1     True
m2     True
m2    False
Name: num, dtype: bool
       price       num
m1  0.830823  0.647249
m2  0.045656  0.709564
             m1        m2
price  0.830823  0.045656
num    0.647249  0.709564


In [19]:
storeframe["total price"] = storeframe["unit price"]*storeframe["number"]

storeframe

unit price  number  total price
store1        1000      25        25000
store2         280     120        33600
store3         900      30        27000

In [20]:
max = np.max(storeframe["total price"])
storeframe[storeframe["total price"] == max]

unit price  number  total price
store2         280     120        33600

In [4]:
#n차원 행렬 생성
import numpy as np
a = np.arange(10).reshape(2,5)

print(a)

print(a.shape)
print(a.ndim) #차원
print(a.size)  #크기
#원소 접근
print(a[0,3])


[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
2
10
3


In [7]:
#행렬 곱
import numpy as np

a = np.array([[1,2,3],[3,2,5]])
b = np.array([[-1,3,5],[1,4,2]])

c = np.dot(a,b.transpose())
print(a)
print(b)
print(c)

[[1 2 3]
 [3 2 5]]
[[-1  3  5]
 [ 1  4  2]]
[[20 15]
 [28 21]]


In [9]:
#마스크 씌우기
a = np.arange(-3,3)

print(a)
print(a<0)
print(a[a<0])
print(a[abs(a)>2])

[-3 -2 -1  0  1  2]
[ True  True  True False False False]
[-3 -2 -1]
[-3]
